service: chkspk

provider:
  name: aws
  runtime: nodejs6.10
  profile: personal
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  convert:
    environment:
      BUCKET_NAME: chkspk-uploads
    handler: convert/handler.handler
    events:
      - http:
          path: users/upload
          method: post

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: chkspk-uploads
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
