service: chkspk

provider:
  name: aws
  runtime: nodejs6.10
  profile: personal

functions:
  hello:
    handler: service/handler.hello

    events:
      - http:
          path: users/create
          method: get

