service: chkspk

provider:
  name: aws
  runtime: nodejs6.10
  profile: personal

functions:
  convert:
    environment:
      BUCKET_NAME: uploads
    handler: convert/handler.handler
    events:
      - s3: uploads
